# Docker

trigger:
  - master
  - patch/*

pr:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  tag: "$(Build.BuildId)"
  imageName: "dockusgeorgus/jcasc"
  major: 0
  minor: 0

name: "$(BuildID)"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "DockerHub"
      repository: "$(imageName)"
      command: "buildAndPush"
      Dockerfile: "**/jenkins/Dockerfile"
      tags: '$(tag)'
    displayName: "Docker build and push jcasc"

  - script: |
      export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
      wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
      tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
      echo "$(imageName)":"$(tag)"
      ./trivy --exit-code 0 --severity HIGH --no-progress "$(imageName)":"$(tag)"
      ./trivy --exit-code 0 --severity CRITICAL --no-progress "$(imageName)":"$(tag)"
    displayName: "Scan image with trivy"
    
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install -U pip
      python -m pip install dockerscan
      dockerscan image info "$(imageName)":"$(tag)"
    displayName: "Install dockerscan"




